In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime

In [4]:
dataset = pd.read_excel('DAIICT Hackathon Data.xlsx', sheet_name='Past In and Out Container Data')
dataset = dataset.dropna()


In [5]:
x = dataset.iloc[:, [1, 4, 5]].values
y = dataset.iloc[:,[-1,-3]].values
# print(type(y[0][0]))

In [6]:
timestt = x[:,0]
dates = [ts.timestamp() for ts in timestt]
print(dates)

[1668216594.0, 1669124439.0, 1670173982.0, 1670256532.0, 1670256532.0, 1670256532.0, 1670256532.0, 1670800832.0, 1671479059.0, 1671786771.0, 1672411465.0, 1672411465.0, 1672019543.0, 1672935299.0, 1672928724.0, 1672928724.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674145461.0, 1674146933.0, 1674146933.0, 1674146933.0, 1674146933.0, 1674146933.0, 1674146933.0, 1674416604.0, 1674416604.0, 1673664190.0, 1673680926.0, 1674228253.0, 1673725585.0, 1674501950.0, 1674147072.0, 1674147072.0, 1675281930.0, 1675281930.0, 1675281930.0, 1675125388.0, 1675353446.0, 1675353459.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675354413.0, 1675380858.0, 1675701559.0, 1675190634.0, 1675191181.0, 1675484091.0, 1675486327.0, 1675491618.0, 1675492213.0, 1675492843.0, 1675495622.0, 1675499100.0, 1675503324.0, 1675505918.0, 1675505918.0, 1675515487.0, 1675309002.0, 16757

In [7]:
# Replace the first column with the extracted dates
x[:, 0] = dates

In [8]:
print(x)

[[1668216594.0 40.0 'E']
 [1669124439.0 40.0 'E']
 [1670173982.0 20.0 'E']
 ...
 [1682438145.0 20.0 'L']
 [1682440907.0 40.0 'E']
 [1682440946.0 40.0 'L']]


In [9]:
timestt2 = y[:,0]
dates2 = []
# dates2 = [float(datetime.strptime(str(ts), "%Y-%m-%d %H:%M:%S.%f").timestamp()) for ts in timestt2]
for ts in timestt2:
  try:
    dates2.append(float(datetime.strptime(str(ts), "%Y-%m-%d %H:%M:%S.%f").timestamp()))
  except ValueError:
    dates2.append(float(datetime.strptime(str(ts), "%Y-%m-%d %H:%M:%S").timestamp()))
y[:, 0] = dates2

In [10]:
print(y)

[[1675732992.804 40.0]
 [1675366422.835 40.0]
 [1676005749.384 20.0]
 ...
 [1682474490.769 20.0]
 [1682488202.025 40.0]
 [1682464069.779 40.0]]


In [11]:
x20 = np.empty_like(x)
x40 = np.empty_like(x)
y20 = np.empty_like(y)
y40 = np.empty_like(y)

x20 = x[x[:, 1] == 20.0]
x40 = x[x[:, 1] == 40.0]


y20 = y[y[:, 1] == 20.0]
y40 = y[y[:, 1] == 40.0]



In [12]:
# Create a dictionary to map labels to numerical values
label_map = {'E': 0, 'L': 1}

# Apply the mapping to the labels column
x20[:, -1] = [label_map[label] for label in x20[:, -1]]
x40[:, -1] = [label_map[label] for label in x40[:, -1]]





In [13]:
print(x20)

[[1670173982.0 20.0 0]
 [1670256532.0 20.0 0]
 [1670256532.0 20.0 0]
 ...
 [1682434783.0 20.0 1]
 [1681875155.0 20.0 1]
 [1682438145.0 20.0 1]]


In [14]:
y20 = np.delete(y20, 1, axis=1)
print(y20)

[[1676005749.384]
 [1677572528.621]
 [1681752196.582]
 ...
 [1682627323.188]
 [1682584049.733]
 [1682474490.769]]


In [15]:
# print(len(x20))
# print(len(y20))
# print(len(x))

In [16]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x20, y20, test_size = 1/2, random_state = 0)

In [17]:
print(X_train)

[[1679399064.0 20.0 0]
 [1680097733.0 20.0 1]
 [1681755611.0 20.0 1]
 ...
 [1680103442.0 20.0 1]
 [1681157925.0 20.0 1]
 [1676398090.0 20.0 1]]


In [18]:
print()

In [19]:
print(X_test)


[[1678365049.0 20.0 0]
 [1678135888.0 20.0 1]
 [1680097733.0 20.0 1]
 ...
 [1682616843.0 20.0 1]
 [1677014319.0 20.0 1]
 [1675608404.0 20.0 0]]


In [20]:
print(y_train)


[[1679393779.099]
 [1680224829.535]
 [1681915334.125]
 ...
 [1680288833.394]
 [1681926358.172]
 [1676458755.127]]


In [21]:
print(y_test)


[[1678392271.436]
 [1678389262.276]
 [1680378841.4]
 ...
 [1682647311.442]
 [1677076797.451]
 [1675642239.343]]


In [22]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [23]:
y_pred = regressor.predict(X_test)


In [24]:
print(len(X_train))

6652


In [25]:
print(len(y_train))

6652


In [ ]:
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()

scx20 = sc_X.fit_transform(x20)
scy20 = sc_y.fit_transform(y20)
regressor = SVR(kernel = 'rbf')
regressor.fit(scx20, scy20)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
